# Generated by Django 5.2.7 on 2025-10-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_ph', models.CharField(max_length=10, unique=True)),
                ('emp_salary', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'crud_app_employee',
            },
        ),
    ]
